#!/bin/sh

. ./gcc.cfg

[ -z "$GCC_DIR" ] && GCC_DIR=gcc

cd $GCC_DIR
REV=$(git log -1 |
      grep git-svn-id |
      awk '{ print $2 }' |
      awk -F@ '{ print $2 }')
cd - > /dev/null
BUILD_DIR=$branch/$REV
if [ -z "$PREFIX" ]; then
  PREFIX=$(pwd)/$BUILD_DIR/usr
else
  DESTDIR=$(pwd)/$BUILD_DIR/install
fi

CPU_NUM=$(/usr/bin/getconf _NPROCESSORS_ONLN)
if [ $CPU_NUM -ge 12 ]; then
  CPU_NUM=12
fi

echo "$(date +"%d %H:%M"): building revision $REV"

if [ -f $branch/last_revision ]; then
  ./gcc-changes
  if [ $? = 2 ]; then
    echo No changes since last build!
    exit 2
  fi
fi

[ -d $BUILD_DIR ] || mkdir -p $BUILD_DIR

if [ -d $BUILD_DIR/usr/bin ]; then
  echo $REV > $branch/last_revision
  exit 0
fi

if [ -f $BUILD_DIR/make.log ]; then
  if grep "Error " $BUILD_DIR/make.log; then
    exit 1
  else
    exit 0
  fi
fi

LANGS=${LANGS-c,c++,fortran}
BOOTSTRAP=${BOOTSTRAP---disable-bootstrap}

CC=${CC-gcc}
CXX=${CXX-g++}

case x"$BOOTSTRAP" in
x*--disable-bootstrap*)
  FLAGS='BOOT_CFLAGS=-g CFLAGS=-g BOOT_CXXFLAGS=-g CXXFLAGS=-g
	 CFLAGS_FOR_TARGET="-O2 -g" CXXFLAGS_FOR_TARGET="-O2 -g"'
  ;;
esac

case $branch in
gcc-4_0-branch)
  ;;
*)
  FLAGS="$FLAGS MAKEINFO=/usr/bin/false"
  ;;
esac

case x"$TARGET" in
xi[3-6]86-*)
  CC="$CC -m32"
  CXX="$CXX -m32"
  PATH=/usr/local32/bin:$PATH
  ;;
esac

case x"$FLAGS" in
x*-mx32*)
  PATH=/usr/localx32/bin:$PATH
  ;;
esac

WITH=
if [ -z "$WITH" ] ;then
  if rpm -q ppl > /dev/null; then
    if grep "with_ppl=no" $GCC_DIR/configure.ac | grep plus; then
      WITH="--without-ppl"
    fi

    if grep "with_cloog=no" $GCC_DIR/configure.ac | grep plus; then
      WITH="$WITH --without-cloog"
    fi
  fi
fi

case $GCC_DIR in
/*) CONFIGURE=$GCC_DIR/configure ;;
*) CONFIGURE=../../../$GCC_DIR/configure ;;
esac

CONFIGURE="$CONFIGURE --prefix=$PREFIX \
    --enable-clocale=gnu \
    --with-system-zlib \
    --with-demangler-in-ld \
    $CHECKING \
    $CONFIG_FLAGS \
    --enable-languages=$LANGS \
    $WITH \
    $TARGET \
    $BOOTSTRAP
"

export CC
export CXX
cd $BUILD_DIR &&
  rm -rf bld &&
  mkdir bld &&
  cd bld &&
  echo $FLAGS $CONFIGURE >../configure.log &&
  eval $FLAGS $CONFIGURE >> ../configure.log 2>&1 &&
  eval `echo make $BOOTSTRAP_MODE $FLAGS -j $CPU_NUM` &> ../make.log &&
# make install must not specify -j x, or some libs like libmudflap won't be 
# installed correctly
  (make install-strip DESTDIR=$DESTDIR || make install DESTDIR=$DESTDIR) &>../install.log &&
  echo $REV > ../../last_revision

if [ $? = 0 ]; then
  [ -n "$DESTDIR" ] && mv $DESTDIR/$PREFIX $DESTDIR/../usr && exit $?
  exit 0
else
  exit 1
fi
