#!/bin/sh

. ./gcc.cfg

[ -z "$GCC_DIR" ] && GCC_DIR=gcc

cd $GCC_DIR
REV=$(git log -1 |
      grep git-svn-id |
      awk '{ print $2 }' |
      awk -F@ '{ print $2 }')
cd -
BUILD_DIR=$branch/$REV
prefix=$(pwd)/$BUILD_DIR/usr

CPU_NUM=$(/usr/bin/getconf _NPROCESSORS_ONLN)
if [ $CPU_NUM -ge 12 ]; then
  CPU_NUM=12
fi

echo "$(date +"%d %H:%M"): building revision $REV"

[ -d $BUILD_DIR ] || mkdir -p $BUILD_DIR

[ -d $BUILD_DIR/usr/bin ] && exit 0

if [ -f $branch/last_revision ]; then
  ./gcc-changes
  if [ $? = 2 ]; then
    echo No changes since last build!
    exit $?
  fi
fi

if [ -f $BUILD_DIR/make.log ]; then
  if grep "Error " $BUILD_DIR/make.log; then
    exit 1
  else
    exit 0
  fi
fi

LANGS=${LANGS-c,c++,fortran}
BOOTSTRAP=${BOOTSTRAP---disable-bootstrap}

case x"$BOOTSTRAP" in
x*--disable-bootstrap*)
  FLAGS="BOOT_CFLAGS=-g CFLAGS=-g"
  ;;
esac

case x"$TARGET" in
xi[3-6]86-*)
  CC="gcc -m32"
  CXX="g++ -m32"
  PATH=/usr/local32/bin:$PATH
  ;;
x*)
  CC="gcc"
  CXX="g++"
  ;;
esac

WITH=
if [ -z "$WITH" ] ;then
  if rpm -q ppl > /dev/null; then
    if grep "with_ppl=no" $GCC_DIR/configure.ac | grep plus; then
      WITH="--without-ppl"
    fi

    if grep "with_cloog=no" $GCC_DIR/configure.ac | grep plus; then
      WITH="$WITH --without-cloog"
    fi
  fi
fi

CONFIGURE="../../../$GCC_DIR/configure --prefix=$prefix  \
    --enable-clocale=gnu \
    --with-system-zlib \
    --with-demangler-in-ld \
    $CHECKING \
    --enable-languages=$LANGS \
    $WITH \
    $TARGET \
    $BOOTSTRAP
"

export CC
export CXX
cd $BUILD_DIR &&
  rm -rf bld &&
  mkdir bld &&
  cd bld &&
  echo $CONFIGURE >../configure.log &&
  $CONFIGURE >> ../configure.log 2>&1 &&
  make $BOOTSTRAP_MODE $FLAGS -j $CPU_NUM &>../make.log &&
# make install must not specify -j x, or some libs like libmudflap won't be 
# installed correctly
  (make install-strip || make install) &>../install.log &&
  echo $REV > ../../last_revision &&
  exit 0

exit 1
