#!/bin/sh

REV="${1}"

. ./gcc.cfg

if [ -z "$REV" ]; then
  echo Need to specify revision number!
  exit 1
fi

[ -z "$GCC_DIR" ] && GCC_DIR=gcc

if [ ! -d $GCC_DIR/.git ]; then
  echo "$GCC_DIR isn't a GCC git source tree!"
  exit 1
fi

echo "Update $GCC_DIR GCC git source tree"

[ -z "$LOG" ] && LOG=`pwd`/git.log

cd $GCC_DIR

rm -f gcc/REVISION

# Check branch status
if [ -z "$branch" ]; then
  branch=$(git status | grep "On branch" | sed -e "s/.*On branch //")
  if [ -z "$branch" ]; then
    echo Need to specify a branch!
  exit 1
  fi
fi

case $branch in
master)
  svn_branch=trunk
  ;;
*)
  svn_branch=$branch
  ;;
esac

commit=$(git log --grep "git-svn-id.*@$REV" origin/$branch |
	 head -1 |
	 awk '{ print $2 }')

if [ -z "$commit" ]; then
  echo Invalid revsion: $REV!
  exit 1
fi

# Check if GCC source is clean
status=$(git status | tail -2 | grep -v "On branch")
case "$status" in
*clean*)
  ;;
*)
  echo GCC $branch branch not clean:
  git status
  exit 1
  ;;
esac

status=$(git status | head -2 | grep -v "On branch")
case "$status" in
*clean*|*bisecting*|*"can be fast-forwarded"*)
  ;;
*)
  echo GCC $branch branch is not clean:
  git status
  exit 1
  ;;
esac

# Check out
echo Check out GCC $branch source tree
git checkout $commit >> $LOG
if [ $? != 0 ]; then
  echo GCC $branch branch failed to check out revision $REV
  exit 1
fi
./contrib/gcc_update --touch >> $LOG

echo "[$svn_branch revision $REV]" > gcc/REVISION
exit 0
